---
title: "Tarea 5"
author: "Francisco_Bahena_Galeana123084"
date: "March 17, 2018"
output: html_document
---


1a) ¿Cuántos “jefes” hay en la tabla empleados? ¿Cuáles son estos jefes: número de empleado, nombre, apellido, título, fecha de nacimiento, fecha en que iniciaron en la empresa, ciudad y país? (atributo reportsto, ocupa explode en tu respuesta)

```{sql, eval=FALSE}
select count(distinct reportsto) as cantidad_de_jefes from northwind.employees where reportsto >0;


select tabla.employeeid, tabla.firstname, tabla.lastname, tabla.title, tabla.birthdate, tabla.hiredate, tabla.city, tabla.country, tabla.empleados from (select employeeid,firstname,lastname,title,birthdate,hiredate,city,country,subord.reportsto,subord.empleados as empleados from northwind.employees emp join (select reportsto,collect_set(firstname) as empleados from northwind.employees where reportsto > 0 group by reportsto) subord on emp.employeeid=subord.reportsto) tabla LATERAL VIEW EXPLODE(tabla.empleados) tabla as empleados;
```

1b) ¿Quién es el segundo “mejor” empleado que más órdenes ha generado? (nombre, apellido, título, cuándo entró a la compañía, número de órdenes generadas, número de órdenes generadas por el mejor empleado (número 1))

```{sql, eval=FALSE}

select emp.firstname,emp.lastname,emp.hiredate,emp.ordenes,LEAD(emp.ordenes,1) OVER(ORDER BY emp.ordenes) max_ordenes from (select e.firstname,e.lastname,e.hiredate,ordens.ordenes from northwind.employees e join (select orders.employeeid,count(*) as ordenes from northwind.orders group by orders.employeeid) ordens on e.employeeid=ordens.employeeid order by ordens.ordenes desc limit 2) emp limit 1;

```

1c) ¿Cuál es el delta de tiempo más grande entre una orden y otra?

```{sql, eval=FALSE}

select todas.orderid, datediff(todas.orderdate,todas.desfase) as delta from (select orderid,orderdate,LAG(orderdate,1) OVER (order by orderdate ASC) as desfase from northwind.orders) as todas order by delta desc limit 1;

```

2a) ¿Qué aerolíneas (nombres) llegan al aeropuerto “Honolulu International Airport”?

```{sql, eval=FALSE}

select  air.IATA_CODE AS codigo_aerolinea, air.AIRLINE as nombre,vuelos.airport as destino from fly.airlines air join (select DISTINCT f.airline,f.destination_airport,f2.airport from fly.flights f join (select a.iata_code,a.airport from fly.airports a where airport="Honolulu International Airport") f2 on f.destination_airport==f2.iata_code) vuelos on air.IATA_CODE=vuelos.airline;

```

2b) ¿En qué horario (hora del día, no importan los minutos) hay salidas del aeropuerto de San Francisco (“SFO”) a “Honolulu International Airport”?

```{sql, eval=FALSE}

select DISTINCT tabla.hora, tabla.origin_airport, tabla.destination_airport from (select SUBSTRING(departure_time,1,2) as hora,departure_time,origin_airport,destination_airport from fly.flights where origin_airport="SFO" and destination_airport="HNL") tabla;

```

2c) ¿Qué día de la semana y en qué aerolínea nos conviene viajar a “Honolulu International Airport” para tener el menor retraso posible?

```{sql, eval=FALSE}

select f3.airline,a.airline,f3.weekday,f3.avg_delay from fly.airlines a join (select SUBSTRING(f2.clave,0,2) as airline,SUBSTRING(f2.clave,3,3) as weekday,f2.avg_delay from (select f1.clave as clave ,AVG(f1.departure_delay) as avg_delay from (select CONCAT(airline,cast(day_of_week as string)) as clave,departure_delay from fly.flights where departure_delay >0 and destination_airport=="HNL") f1 group by f1.clave order by avg_delay) f2) f3 on a.iata_code=f3.airline limit 1;

```

2d) ¿Cuál es el aeropuerto con mayor tráfico de entrada?

```{sql, eval=FALSE}
  
select f1.destination_airport,a.airport,f1.vuelos_entrada from fly.airports a join (select destination_airport,count(*) as vuelos_entrada from fly.flights group by destination_airport) f1 on a.iata_code=f1.destination_airport order by f1.vuelos_entrada desc limit 1;
  
```


2e)¿Cuál es la aerolínea con mayor retraso de salida por día de la semana?

```{sql, eval=FALSE}
select t1.weekday,t2.aerolinea,t1.retraso_max from (select f1.day_of_week as weekday,MAX(f1.retraso) as retraso_max from (select f.airline as aerolinea,f.day_of_week,MAX(f.departure_delay) as retraso from fly.flights f group by f.day_of_week,f.airline) f1 group by f1.day_of_week) t1 join (select f.airline as aerolinea,f.day_of_week,MAX(f.departure_delay) as retraso from fly.flights f group by f.day_of_week,f.airline) t2 on t1.retraso_max=t2.retraso;  
```


2f) ¿Cuál es la tercer aerolínea con menor retraso de salida los lunes (day of week = 2)?

```{sql, eval=FALSE}
select * from (select airline,day_of_week,avg(departure_delay) as avg_delay from fly.flights where day_of_week=2 group by airline,day_of_week order by avg_delay asc limit 3) t1 order by t1.avg_delay desc limit 1;
```


2g) ¿Cuál es el aeropuerto origen que llega a la mayor cantidad de aeropuertos destino diferentes?

```{sql, eval=FALSE}
select t1.origin_airport,a.airport,t1.destinos from fly.airports a join (select origin_airport,COUNT(DISTINCT destination_airport) as destinos from fly.flights group by origin_airport order by destinos desc limit 1) t1 on a.iata_code=t1.origin_airport;
```

