flights = load '$INPUT/flights.csv' using PigStorage(',') as (YEAR,MONTH,DAY,DAY_OF_WEEK,AIRLINE,FLIGHT_NUMBER,TAIL_NUMBER,ORIGIN_AIRPORT,DESTINATION_AIRPORT,SCHEDULED_DEPARTURE,DEPARTURE_TIME,DEPARTURE_DELAY,TAXI_OUT,WHEELS_OFF,SCHEDULED_TIME,ELAPSED_TIME,AIR_TIME,DISTANCE,WHEELS_ON,TAXI_IN,SCHEDULED_ARRIVAL,ARRIVAL_TIME,ARRIVAL_DELAY,DIVERTED,CANCELLED,CANCELLATION_REASON,AIR_SYSTEM_DELAY,SECURITY_DELAY,AIRLINE_DELAY,LATE_AIRCRAFT_DELAY,WEATHER_DELAY);
airports = load '$INPUT/airports.csv' using PigStorage(',') as (IATA_CODE,AIRPORT,CITY,STATE,COUNTRY,LATITUDE,LONGITUDE);
flights_airports = JOIN flights by DESTINATION_AIRPORT, airports by IATA_CODE; 
dest_honolulu = FILTER flights_airports by AIRPORT in ('Honolulu International Airport');
dest_group = GROUP dest_honolulu ALL;
total = FOREACH dest_group GENERATE COUNT(dest_honolulu);

store total into '$OUTPUT/output1/' using PigStorage(',', '-schema');
