flights = load '$INPUT/flights.csv' using PigStorage(',') as (YEAR,MONTH,DAY,DAY_OF_WEEK,AIRLINE,FLIGHT_NUMBER,TAIL_NUMBER,ORIGIN_AIRPORT,DESTINATION_AIRPORT,SCHEDULED_DEPARTURE,DEPARTURE_TIME,DEPARTURE_DELAY,TAXI_OUT,WHEELS_OFF,SCHEDULED_TIME,ELAPSED_TIME,AIR_TIME,DISTANCE,WHEELS_ON,TAXI_IN,SCHEDULED_ARRIVAL,ARRIVAL_TIME,ARRIVAL_DELAY,DIVERTED,CANCELLED,CANCELLATION_REASON,AIR_SYSTEM_DELAY,SECURITY_DELAY,AIRLINE_DELAY,LATE_AIRCRAFT_DELAY,WEATHER_DELAY);
flights_cancelled = FILTER flights by CANCELLED ==1;
cancelled_selected = FOREACH flights_cancelled GENERATE DAY_OF_WEEK, CANCELLED;
cancelled_group = GROUP cancelled_selected BY DAY_OF_WEEK;
cont = FOREACH cancelled_group GENERATE group as DAY_OF_WEEK, COUNT($1) as n;
ranked = rank cont by n DESC;
limited_ranked = limit ranked 1;

store limited_ranked into '$OUTPUT/output3/' using PigStorage(',', '-schema');
