---
title: "Tarea 4"
author: "Cristian Challu"
date: "5 de marzo de 2018"
output: html_document
---

#Ejercicio A


```{r, eval=FALSE}

products = load 's3://cristian-challu/tarea4/products.csv' using PigStorage(',') as (productid:chararray, productname:chararray, supplierid:chararray, categoryid:chararray, quantityperunit:int, unitprice:float, unitsinstock:int, unitsonorder:int, reorderlevel:int, discounted:int);

orders = load 's3://cristian-challu/tarea4/order_details.csv' using PigStorage(',') as (orderid:chararray, productid:chararray, unitprice:float, quantity:int, discount:float);

orders_grouped = GROUP orders by productid;

products_count = FOREACH orders_grouped GENERATE group AS productid,COUNT($1) as amount;

products_named = JOIN products_count BY productid, products BY productid;

products_ranked = RANK products_named BY amount DESC;

result = LIMIT products_ranked 1;

STORE result INTO 's3://cristian-challu/tarea4/output/output_a_1/' using PigStorage(',');

```


#Ejercicio B 1

```{r, eval=FALSE}

flights = load 's3://cristian-challu/tarea4/flights.csv' using PigStorage(',') as (year:int, month:int, day:int, day_of_week:int, airline:chararray, flight_number:int, tail_number:chararray, origin_airport:chararray, destination_airport:chararray, scheduled_departure:int, departure_time:int, departure_delay:int, taxi_out:int, wheels_off:int, scheduled_time:int, elapsed_time:int, air_time:int, distance:int, wheels_on:int, taxi_in:int, scheduled_arrival:int, arrival_time:int, arrival_delay:int, diverted:int, cancelled:int, cancellation_reason:chararray, air_system_delay:chararray, security_delay:chararray, airline_delay:chararray, late_aircraft_delay:chararray, weather_delay:chararray);

airports = load 's3://cristian-challu/tarea4/airports.csv' using PigStorage(',') as (iata_code:chararray, airport:chararray, city:chararray, state:chararray, country:chararray, latitude:float, longitude:float);

airpors_filtered = FILTER airports BY airport == 'Honolulu International Airport';

flights_joined = JOIN flights BY destination_airport, airpors_filtered BY iata_code;

flights_joined_grouped = GROUP flights_joined ALL;

result = FOREACH flights_joined_grouped GENERATE COUNT(flights_joined) as amount;

STORE result INTO 's3://cristian-challu/tarea4/output/output_b_1/' using PigStorage(',');

```



#Ejercicio B 2

```{r, eval=FALSE}
flights = load 's3://cristian-challu/tarea4/flights.csv' using PigStorage(',') as (year:int, month:int, day:int, day_of_week:int, airline:chararray, flight_number:int, tail_number:chararray, origin_airport:chararray, destination_airport:chararray, scheduled_departure:int, departure_time:int, departure_delay:int, taxi_out:int, wheels_off:int, scheduled_time:int, elapsed_time:int, air_time:int, distance:int, wheels_on:int, taxi_in:int, scheduled_arrival:int, arrival_time:int, arrival_delay:int, diverted:int, cancelled:int, cancellation_reason:chararray, air_system_delay:chararray, security_delay:chararray, airline_delay:chararray, late_aircraft_delay:chararray, weather_delay:chararray);

airlines = load 's3://cristian-challu/tarea4/airlines.csv' using PigStorage(',') as (iata_code:chararray,airline:chararray);

flights_ordered = ORDER flights BY arrival_delay DESC;

flight_max_delay = LIMIT flights_ordered 1;

result = JOIN flight_max_delay BY airline, airlines BY iata_code;

STORE result INTO 's3://cristian-challu/tarea4/output/output_b_2/' using PigStorage(',');

```



#Ejercicio B 3

```{r, eval=FALSE}
flights = load 's3://cristian-challu/tarea4/flights.csv' using PigStorage(',') as (year:int, month:int, day:int, day_of_week:int, airline:chararray, flight_number:int, tail_number:chararray, origin_airport:chararray, destination_airport:chararray, scheduled_departure:int, departure_time:int, departure_delay:int, taxi_out:int, wheels_off:int, scheduled_time:int, elapsed_time:int, air_time:int, distance:int, wheels_on:int, taxi_in:int, scheduled_arrival:int, arrival_time:int, arrival_delay:int, diverted:int, cancelled:int, cancellation_reason:chararray, air_system_delay:chararray, security_delay:chararray, airline_delay:chararray, late_aircraft_delay:chararray, weather_delay:chararray);

flights_2 = FOREACH flights GENERATE day_of_week AS day, cancelled;

flights_cancelled = FILTER flights_2 BY cancelled == 1;

flights_cancelled_grouped = GROUP flights_cancelled BY day;

days = FOREACH flights_cancelled_grouped GENERATE group AS day, COUNT($1) as amount;

result = RANK days BY amount DESC;

STORE result INTO 's3://cristian-challu/tarea4/output/output_b_3/' using PigStorage(',');

```


#Ejercicio B 4

```{r, eval=FALSE}
flights = load 's3://cristian-challu/tarea4/flights.csv' using PigStorage(',') as (year:int, month:int, day:int, day_of_week:int, airline:chararray, flight_number:int, tail_number:chararray, origin_airport:chararray, destination_airport:chararray, scheduled_departure:int, departure_time:int, departure_delay:int, taxi_out:int, wheels_off:int, scheduled_time:int, elapsed_time:int, air_time:int, distance:int, wheels_on:int, taxi_in:int, scheduled_arrival:int, arrival_time:int, arrival_delay:int, diverted:int, cancelled:int, cancellation_reason:chararray, air_system_delay:chararray, security_delay:chararray, airline_delay:chararray, late_aircraft_delay:chararray, weather_delay:chararray);

airports = load 's3://cristian-challu/tarea4/airports.csv' using PigStorage(',') as (iata_code:chararray, airport:chararray, city:chararray, state:chararray, country:chararray, latitude:float, longitude:float);

flights_2 = FOREACH flights GENERATE origin_airport, cancelled;

flights_cancelled = FILTER flights_2 BY cancelled == 1;

flights_cancelled_grouped = GROUP flights_cancelled BY origin_airport;

airports_amounts = FOREACH flights_cancelled_grouped GENERATE group AS origin_airport, COUNT($1) as amount;

airports_amounts_17 = FILTER airports_amounts BY amount == 17;

amounts_joined = JOIN airports_amounts_17 BY origin_airport, airports BY iata_code;

result = FOREACH amounts_joined GENERATE airport, amount;

STORE result INTO 's3://cristian-challu/tarea4/output/output_b_4/' using PigStorage(',');

```


#Ejercicio B 5

```{r, eval=FALSE}
flights = load 's3://cristian-challu/tarea4/flights.csv' using PigStorage(',') as (year:int, month:int, day:int, day_of_week:int, airline:chararray, flight_number:int, tail_number:chararray, origin_airport:chararray, destination_airport:chararray, scheduled_departure:int, departure_time:int, departure_delay:int, taxi_out:int, wheels_off:int, scheduled_time:int, elapsed_time:int, air_time:int, distance:int, wheels_on:int, taxi_in:int, scheduled_arrival:int, arrival_time:int, arrival_delay:int, diverted:int, cancelled:int, cancellation_reason:chararray, air_system_delay:chararray, security_delay:chararray, airline_delay:chararray, late_aircraft_delay:chararray, weather_delay:chararray);

airports = load 's3://cristian-challu/tarea4/airports.csv' using PigStorage(',') as (iata_code:chararray, airport:chararray, city:chararray, state:chararray, country:chararray, latitude:float, longitude:float);

flights_2 = FOREACH flights GENERATE origin_airport, cancelled;

flights_cancelled = FILTER flights_2 BY cancelled == 1;

flights_cancelled_grouped = GROUP flights_cancelled BY origin_airport;

airports_amounts = FOREACH flights_cancelled_grouped GENERATE group AS origin_airport, COUNT($1) as amount;

amounts_joined = JOIN airports_amounts BY origin_airport, airports BY iata_code;

airports_amounts_ordered = ORDER amounts_joined BY amount DESC;

airports_max_cancelled = LIMIT airports_amounts_ordered 5;

result = FOREACH airports_max_cancelled GENERATE airport, amount;

STORE result INTO 's3://cristian-challu/tarea4/output/output_b_5/' using PigStorage(',', '-schema');

```

#Ejercicio B 6

```{r, eval=FALSE}
flights = load 's3://cristian-challu/tarea4/flights.csv' using PigStorage(',') as (year:int, month:int, day:int, day_of_week:int, airline:chararray, flight_number:int, tail_number:chararray, origin_airport:chararray, destination_airport:chararray, scheduled_departure:int, departure_time:int, departure_delay:int, taxi_out:int, wheels_off:int, scheduled_time:int, elapsed_time:int, air_time:int, distance:int, wheels_on:int, taxi_in:int, scheduled_arrival:int, arrival_time:int, arrival_delay:int, diverted:int, cancelled:int, cancellation_reason:chararray, air_system_delay:chararray, security_delay:chararray, airline_delay:chararray, late_aircraft_delay:chararray, weather_delay:chararray);

airports = load 's3://cristian-challu/tarea4/airports.csv' using PigStorage(',') as (iata_code:chararray, airport:chararray, city:chararray, state:chararray, country:chararray, latitude:float, longitude:float);

airports_flights_joined = JOIN flights BY destination_airport, airports BY iata_code;

air_flights_grouped = GROUP airports_flights_joined BY flight_number;

results_1 = FOREACH air_flights_grouped { unique_airports = DISTINCT airports_flights_joined.airport; GENERATE group AS flight_number, COUNT(unique_airports) as amount, unique_airports;};

results_order = ORDER results_1 BY amount DESC;

result = LIMIT results_order 5;

STORE result INTO 's3://cristian-challu/tarea4/output/output_b_6/' using PigStorage(',', '-schema');

```